"""add_rbac_fields

Revision ID: a8007ce4c758
Revises: 7d82d4f9f341
Create Date: 2025-12-04 09:41:34.520665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a8007ce4c758'
down_revision: Union[str, Sequence[str], None] = '7d82d4f9f341'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('favorites', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.add_column('posts', sa.Column('comment_count', sa.Integer(), nullable=True))
    op.add_column('posts', sa.Column('lock_reason', sa.String(length=500), nullable=True))
    op.add_column('posts', sa.Column('locked_at', sa.DateTime(), nullable=True))
    op.add_column('posts', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.alter_column('posts', 'upvotes',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('posts', 'downvotes',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('posts', 'is_locked',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('posts', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('posts', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('posts', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.add_column('users', sa.Column('ban_reason', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('banned_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('banned_by_id', sa.Integer(), nullable=True))
    op.alter_column('users', 'firebase_uid',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.alter_column('users', 'bio',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('users', 'role_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'is_banned',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.create_foreign_key(None, 'users', 'users', ['banned_by_id'], ['id'])
    op.alter_column('votes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('votes', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.alter_column('users', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'is_banned',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'role_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('users', 'bio',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    op.alter_column('users', 'firebase_uid',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.drop_column('users', 'banned_by_id')
    op.drop_column('users', 'banned_at')
    op.drop_column('users', 'ban_reason')
    op.alter_column('posts', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('posts', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('posts', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('posts', 'is_locked',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('posts', 'downvotes',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('posts', 'upvotes',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('posts', 'deleted_at')
    op.drop_column('posts', 'locked_at')
    op.drop_column('posts', 'lock_reason')
    op.drop_column('posts', 'comment_count')
    op.alter_column('favorites', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###
